# Generated by Django 5.1.1 on 2024-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
