# Generated by Django 5.1.1 on 2024-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memo_is_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
